routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::middleware('auth')->group(function() {
    Route::get('/', 'MedicineController@index')->name('index');

    Route::resource('medicine', 'MedicineController')->except('show');
    Route::resource('manufacturer', 'ManufacturerController')->except('show');
    Route::resource('substance', 'SubstanceController')->except('show');
});

Auth::routes();

app/Models/Manufacturer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Manufacturer extends Model
{
    use HasFactory;

    protected $fillable = [];

    protected $guarded = [];

    public $timestamps = false;

    public function getLinkAttribute($value)
    {
        return Str::startsWith($value, ['http', 'https']) ? $value : 'http://' . $value;
    }
}

app/Http/Controllers/API/ManufacturerController.php
<?php

namespace App\Http\Controllers\API;

use App\Models\Manufacturer;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use Illuminate\Http\Resources\Json\ResourceCollection;

class ManufacturerController extends Controller
{
    public function index()
    {
        $result = Manufacturer::orderBy('name', 'asc')->paginate();

        return new ResourceCollection($result);
    }

    public function store(Request $request)
    {
        $this->validator($request->all())->validate();

        return Manufacturer::create($request->all());
    }

    public function update(Request $request, Manufacturer $manufacturer)
    {
        $this->validator($request->all())->validate();

        $manufacturer->update($request->all());

        return $manufacturer;
    }

    public function destroy(Manufacturer $manufacturer)
    {
        $manufacturer->delete();

        return response()->json(['message' => 'Success'], 200);
    }

    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => 'required',
            'link' => 'nullable|url',
        ]);
    }
}

app/Http/Controllers/ManufacturerController.php
<?php

namespace App\Http\Controllers;

use App\Models\Manufacturer;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class ManufacturerController extends Controller
{
    public function index()
    {
        $result = Manufacturer::orderBy('name', 'asc')->paginate();

        return view('manufacturer.index', ['result' => $result]);
    }

    public function create()
    {
        $model = new Manufacturer();

        return view('manufacturer.form', ['model' => $model]);
    }

    public function store(Request $request)
    {
        $this->validator($request->all())->validate();

        Manufacturer::create($request->all());

        return redirect()->route('manufacturer.index')->with('success', 'Запись создана.');
    }

    public function edit(Manufacturer $manufacturer)
    {
        return view('manufacturer.form', ['model' => $manufacturer]);
    }

    public function update(Request $request, Manufacturer $manufacturer)
    {
        $this->validator($request->all())->validate();

        $manufacturer->update($request->all());

        return redirect()->route('manufacturer.index')->with('success', 'Запись обновлена.');
    }

    public function destroy(Manufacturer $manufacturer)
    {
        $manufacturer->delete();

        return redirect()->route('manufacturer.index')->with('success', 'Запись удалена.');
    }

    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => 'required',
            'link' => 'nullable|url',
        ]);
    }
}

resources/views/manufacturer/form.blade.php
@extends('layouts.app')

@section('content')
    {{ aire()->resourceful($model, 'manufacturer') }}
    <div class="card">
        <h5 class="card-header">
            {{ $model->exists ? 'Редактирование: "' . $model->name . '"' : 'Добавление нового производителя' }}

        </h5>
        <div class="card-body">
            {{ aire()->input('name', 'Название') }}
            {{ aire()->input('link', 'Ссылка') }}
        </div>
        <div class="card-footer">
            <button class="btn btn-primary">Сохранить</button>
            <a href="{{ route('manufacturer.index') }}" class="btn btn-outline-secondary">Назад к списку</a>
            @if($model->exists)
                <a href="{{ route('manufacturer.destroy', $model) }}" class="btn btn-outline-danger float-right" data-action="destroy_model">Удалить</a>
            @endif
        </div>
    </div>
    {{ aire()->close() }}
@endsection

resources/views/manufacturer/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="card">
        <h5 class="card-header">
            Производители ({{ $result->total() }})
            <a href="{{ route('manufacturer.create') }}" class="btn btn-sm btn-secondary">Создать</a>
        </h5>
        <table class="table border-none text-center table-hover mb-0">
            <thead>
            <tr>
                <th class="align-middle border-right">ID</th>
                <th class="align-middle border-right">Название</th>
                <th class="align-middle border-right">Ссылка</th>
                <th class="align-middle">Действия</th>
            </tr>
            </thead>
            <tbody>
            @foreach($result as $item)
                <tr>
                    <td class="align-middle border-right">{{ $item->id }}</td>
                    <td class="align-middle border-right">
                        <a href="{{ route('manufacturer.edit', $item) }}">{{ $item->name }}</a>
                    </td>
                    <td class="align-middle border-right">
                        @if($item->link)
                            <a href="{{ $item->link }}" target="_blank" rel="nofollow">{{ $item->link }}</a>
                        @else
                            N/A
                        @endif
                    </td>
                    <td class="align-middle">
                        <a href="{{ route('manufacturer.edit', $item) }}" class="btn btn-sm btn-outline-secondary">Редакткировать</a>
                        <a href="{{ route('manufacturer.destroy', $item) }}" class="btn btn-sm btn-outline-secondary" data-action="destroy">Удалить</a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        @if($result->hasPages())
            <div class="card-footer">
                {!! $result->links() !!}
            </div>
        @endif
    </div>
@endsection