routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::middleware('auth')->group(function() {
    Route::get('/', 'MedicineController@index')->name('index');

    Route::resource('medicine', 'MedicineController')->except('show');
    Route::resource('manufacturer', 'ManufacturerController')->except('show');
    Route::resource('substance', 'SubstanceController')->except('show');
});

Auth::routes();

app/Models/Substance.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Substance extends Model
{
    use HasFactory;

    protected $fillable = [];

    protected $guarded = [];

    public $timestamps = false;
}

app/Http/Controllers/API/SubstanceController.php
<?php

namespace App\Http\Controllers\API;

use App\Models\Substance;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use Illuminate\Http\Resources\Json\ResourceCollection;

class SubstanceController extends Controller
{
    public function index()
    {
        $result = Substance::orderBy('name', 'asc')->paginate();

        return new ResourceCollection($result);
    }

    public function store(Request $request)
    {
        $this->validator($request->all())->validate();

        return Substance::create($request->all());
    }

    public function update(Request $request, Substance $manufacturer)
    {
        $this->validator($request->all())->validate();

        $manufacturer->update($request->all());

        return $manufacturer;
    }

    public function destroy(Substance $manufacturer)
    {
        $manufacturer->delete();

        return response()->json(['message' => 'Success'], 200);
    }

    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => 'required',
        ]);
    }
}

app/Http/Controllers/SubstanceController.php
<?php

namespace App\Http\Controllers;

use App\Models\Substance;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class SubstanceController extends Controller
{
    public function index()
    {
        $result = Substance::orderBy('name', 'asc')->paginate();

        return view('substance.index', ['result' => $result]);
    }

    public function create()
    {
        $model = new Substance();

        return view('substance.form', ['model' => $model]);
    }

    public function store(Request $request)
    {
        $this->validator($request->all())->validate();

        Substance::create($request->all());

        return redirect()->route('substance.index')->with('success', 'Запись создана.');
    }

    public function edit(Substance $substance)
    {
        return view('substance.form', ['model' => $substance]);
    }

    public function update(Request $request, Substance $substance)
    {
        $this->validator($request->all())->validate();

        $substance->update($request->all());

        return redirect()->route('substance.index')->with('success', 'Запись обновлена.');
    }

    public function destroy(Substance $substance)
    {
        $substance->delete();

        return redirect()->route('substance.index')->with('success', 'Запись удалена.');
    }

    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => 'required',
        ]);
    }
}

resources/views/substance/form.blade.php
@extends('layouts.app')

@section('content')
    {{ aire()->resourceful($model, 'substance') }}
    <div class="card">
        <h5 class="card-header">
            {{ $model->exists ? 'Редактирование: "' . $model->name . '"' : 'Добавление нового действующего вещества' }}

        </h5>
        <div class="card-body">
            {{ aire()->input('name', 'Название') }}
        </div>
        <div class="card-footer">
            <button class="btn btn-primary">Сохранить</button>
            <a href="{{ route('substance.index') }}" class="btn btn-outline-secondary">Назад к списку</a>
            @if($model->exists)
                <a href="{{ route('substance.destroy', $model) }}" class="btn btn-outline-danger float-right" data-action="destroy_model">Удалить</a>
            @endif
        </div>
    </div>
    {{ aire()->close() }}
@endsection

resources/views/substance/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="card">
        <h5 class="card-header">
            Действующие вещества ({{ $result->total() }})
            <a href="{{ route('substance.create') }}" class="btn btn-sm btn-secondary">Создать</a>
        </h5>
        <table class="table border-none text-center table-hover mb-0">
            <thead>
            <tr>
                <th class="align-middle border-right">ID</th>
                <th class="align-middle border-right">Название</th>
                <th class="align-middle">Действия</th>
            </tr>
            </thead>
            <tbody>
            @foreach($result as $item)
                <tr>
                    <td class="align-middle border-right">{{ $item->id }}</td>
                    <td class="align-middle border-right">
                        <a href="{{ route('substance.edit', $item) }}">{{ $item->name }}</a>
                    </td>
                    <td class="align-middle">
                        <a href="{{ route('substance.edit', $item) }}" class="btn btn-sm btn-outline-secondary">Редакткировать</a>
                        <a href="{{ route('substance.destroy', $item) }}" class="btn btn-sm btn-outline-secondary" data-action="destroy">Удалить</a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        @if($result->hasPages())
            <div class="card-footer">
                {!! $result->links() !!}
            </div>
        @endif
    </div>
@endsection