routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::middleware('auth')->group(function() {
    Route::get('/', 'MedicineController@index')->name('index');

    Route::resource('medicine', 'MedicineController')->except('show');
    Route::resource('manufacturer', 'ManufacturerController')->except('show');
    Route::resource('substance', 'SubstanceController')->except('show');
});

Auth::routes();

app/Models/Medicine.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Medicine extends Model
{
    use HasFactory;

    protected $fillable = [];

    protected $guarded = [];

    public function manufacturer()
    {
        return $this->belongsTo('App\Models\Manufacturer')->withDefault();
    }

    public function substance()
    {
        return $this->belongsTo('App\Models\Substance')->withDefault();
    }
}

app/Http/Controllers/API/MedicineController.php
<?php

namespace App\Http\Controllers\API;

use App\Models\Medicine;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use Illuminate\Http\Resources\Json\ResourceCollection;

class MedicineController extends Controller
{
    public function index(Request $request)
    {
        $query = Medicine::orderBy('name', 'asc')
            ->with(['manufacturer', 'substance']);

        $filter = $request->get('filter');

        if (isset($filter['manufacturer_id'])) {
            $query->where('manufacturer_id', $filter['manufacturer_id']);
        }

        if (isset($filter['substance_id'])) {
            $query->where('substance_id', $filter['substance_id']);
        }

        $result = $query->paginate();

        return new ResourceCollection($result);
    }

    public function store(Request $request)
    {
        $this->validator($request->all())->validate();

        return Medicine::create($request->all());
    }

    public function update(Request $request, Medicine $medicine)
    {
        $this->validator($request->all())->validate();

        $medicine->update($request->all());

        return $medicine;
    }

    public function destroy(Medicine $medicine)
    {
        $medicine->delete();

        return response()->json(['message' => 'Success'], 200);
    }

    protected function validator(array $data)
    {
        return Validator::make($data, [
            'manufacturer_id' => 'required|exists:manufacturers,id',
            'substance_id' => 'required|exists:substances,id',
            'name' => 'required',
            'price' => 'required|numeric',
        ]);
    }
}

app/Http/Controllers/MedicineController.php
<?php

namespace App\Http\Controllers;

use App\Models\Medicine;
use App\Models\Substance;
use App\Models\Manufacturer;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class MedicineController extends Controller
{
    public function index(Request $request)
    {
        $query = Medicine::orderBy('name', 'asc')
            ->with(['manufacturer', 'substance']);

        $filter = $request->get('filter');

        if (isset($filter['manufacturer_id'])) {
            $query->where('manufacturer_id', $filter['manufacturer_id']);
        }

        if (isset($filter['substance_id'])) {
            $query->where('substance_id', $filter['substance_id']);
        }

        $result = $query->paginate();

        return view('medicine.index', ['result' => $result]);
    }

    public function create()
    {
        $model = new Medicine();

        $manufacturer_list = Manufacturer::orderBy('name', 'asc')->get()->pluck('name', 'id');
        $substance_list = Substance::orderBy('name', 'asc')->get()->pluck('name', 'id');

        return view('medicine.form', ['model' => $model, 'manufacturer_list' => $manufacturer_list, 'substance_list' => $substance_list]);
    }

    public function store(Request $request)
    {
        $this->validator($request->all())->validate();

        Medicine::create($request->all());

        return redirect()->route('medicine.index')->with('success', 'Запись создана.');
    }

    public function edit(Medicine $medicine)
    {
        $manufacturer_list = Manufacturer::orderBy('name', 'asc')->get()->pluck('name', 'id');
        $substance_list = Substance::orderBy('name', 'asc')->get()->pluck('name', 'id');

        return view('medicine.form', ['model' => $medicine, 'manufacturer_list' => $manufacturer_list, 'substance_list' => $substance_list]);
    }

    public function update(Request $request, Medicine $medicine)
    {
        $this->validator($request->all())->validate();

        $medicine->update($request->all());

        return redirect()->route('medicine.index')->with('success', 'Запись обновлена.');
    }

    public function destroy(Medicine $medicine)
    {
        $medicine->delete();

        return redirect()->route('medicine.index')->with('success', 'Запись удалена.');
    }

    protected function validator(array $data)
    {
        return Validator::make($data, [
            'manufacturer_id' => 'required|exists:manufacturers,id',
            'substance_id' => 'required|exists:substances,id',
            'name' => 'required',
            'price' => 'required|numeric',
        ]);
    }
}

resources/views/medicine/form.blade.php
@extends('layouts.app')

@section('content')
    {{ aire()->resourceful($model, 'medicine') }}
    <div class="card">
        <h5 class="card-header">
            {{ $model->exists ? 'Редактирование: "' . $model->name . '"' : 'Добавление нового лекарственного средства' }}

        </h5>
        <div class="card-body">
            {{ aire()->select($manufacturer_list, 'manufacturer_id', 'Производитель')->prependEmptyOption('Выберите из списка') }}
            {{ aire()->select($substance_list, 'substance_id', 'Действующее вещество')->prependEmptyOption('Выберите из списка') }}
            {{ aire()->input('name', 'Название') }}
            {{ aire()->input('price', 'Цена') }}
        </div>
        <div class="card-footer">
            <button class="btn btn-primary">Сохранить</button>
            <a href="{{ route('medicine.index') }}" class="btn btn-outline-secondary">Назад к списку</a>
            @if($model->exists)
                <a href="{{ route('medicine.destroy', $model) }}" class="btn btn-outline-danger float-right" data-action="destroy_model">Удалить</a>
            @endif
        </div>
    </div>
    {{ aire()->close() }}
@endsection

resources/views/medicine/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="card">
        <h5 class="card-header">
            Лекарственные средства ({{ $result->total() }})
            <a href="{{ route('medicine.create') }}" class="btn btn-sm btn-secondary">Создать</a>
            @if(request()->has('filter'))
                <a href="{{ route('medicine.index') }}" class="btn btn-sm btn-outline-primary">сбросить фильтр</a>
            @endif
        </h5>
        <table class="table border-none text-center table-hover mb-0">
            <thead>
            <tr>
                <th class="align-middle border-right">ID</th>
                <th class="align-middle border-right">Название</th>
                <th class="align-middle border-right">Производитель</th>
                <th class="align-middle border-right">Ингредиент</th>
                <th class="align-middle">Действия</th>
            </tr>
            </thead>
            <tbody>
            @foreach($result as $item)
                <tr>
                    <td class="align-middle border-right">{{ $item->id }}</td>
                    <td class="align-middle border-right">
                        <a href="{{ route('medicine.edit', $item) }}">{{ $item->name }}</a>
                    </td>
                    <td class="align-middle border-right">
                        @if($item->manufacturer->exists)
                            <a href="{{ route('medicine.index', ['filter[manufacturer_id]' => $item->manufacturer_id]) }}">{{ $item->manufacturer->name }}</a>
                        @else
                            N/A
                        @endif
                    </td>
                    <td class="align-middle border-right">
                        @if($item->substance->exists)
                            <a href="{{ route('medicine.index', ['filter[substance_id]' => $item->substance]) }}">{{ $item->substance->name }}</a>
                        @else
                            N/A
                        @endif
                    </td>
                    <td class="align-middle">
                        <a href="{{ route('medicine.edit', $item) }}" class="btn btn-sm btn-outline-secondary">Редакткировать</a>
                        <a href="{{ route('medicine.destroy', $item) }}" class="btn btn-sm btn-outline-secondary" data-action="destroy">Удалить</a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        @if($result->hasPages())
            <div class="card-footer">
                {!! $result->withQueryString()->links() !!}
            </div>
        @endif
    </div>
@endsection